- type: job
  id: Surgeon
  name: job-name-surgeon
  description: job-description-surgeon
  playTimeTracker: JobSurgeon
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 18000 #5 hrs
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 7200 #2 hrs
  startingGear: SurgeonGear
  icon: "JobIconSurgeon"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  special:
  - !type:AddComponentSpecial
    components:
    - type: SurgerySpeedModifier
      speedModifier: 2.5

- type: startingGear
  id: SurgeonGear
  equipment:
    ears: ClothingHeadsetMedical
    belt: ClothingBeltSurgicalBoardFilled
    shoes: ClothingShoesColorWhite
    id: SurgeonPDA
    mask: ClothingMaskSterile
    gloves: ClothingHandsGlovesNitrile
